# Generated by Django 5.1.3 on 2024-11-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('GNSS', 'GNSS'), ('Total Station', 'Total Station'), ('Level Instrumet', 'Level Instrument'), ('Drone', 'Drone')], max_length=50)),
                ('status', models.CharField(default='In Store', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyorEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_equipment', models.ManyToManyField(blank=True, to='inventory.equipment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
