# Generated by Django 5.1.3 on 2025-10-01 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tripod', 'Tripod'), ('levelling_staff', 'Levelling Staff'), ('GNSS Battery', 'GNSS Battery'), ('Pole', 'Pole'), ('Mini Prism', 'Mini Prism'), ('Sheet', 'Sheet'), ('Total Station prism', 'Total Station Prism'), ('Radio', 'Radio'), ('tracking_rod', 'Tracking Rod'), ('reflector', 'Reflector'), ('gps_extension_bar', 'GPS Extension Bar'), ('bar_port', 'Bar Port'), ('powerbank', 'Powerbank'), ('tribach', 'Tribach'), ('external_radio_antenna', 'External Radio Antenna'), ('Data Lpgger', 'Data Logger')], max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Unique serial number for the accessory', max_length=50, null=True)),
                ('surveyor_responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Bad', 'Bad')], default='Good', max_length=20, null=True)),
                ('return_status', models.CharField(blank=True, choices=[('In Use', 'In Use'), ('Returning', 'Returning'), ('Delivering', 'Delivering'), ('With Chief Surveyor', 'With Chief Surveyor'), ('In Store', 'In Store'), ('Returned', 'Returned')], default='Returned', max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessory_images/')),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Delivering', 'Delivering'), ('Cancelled', 'Cancelled')], max_length=10, null=True)),
                ('chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_accessories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('released', 'Released'), ('returned', 'Returned'), ('status_changed', 'Status Changed'), ('image_uploaded', 'Image Uploaded')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_return_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_return_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.accessory')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_changes', to=settings.AUTH_USER_MODEL)),
                ('new_chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_accessory_history', to=settings.AUTH_USER_MODEL)),
                ('previous_chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_accessory_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentsInSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GNSS base-roover', 'GNSS base-roover'), ('GNSS roover', 'GNSS roover'), ('GNSS base', 'GNSS base'), ('Total Station', 'Total Station'), ('Level Instruments', 'Level Instrument'), ('Drone', 'Drone'), ('Eco Sounder', 'Eco Sounder'), ('Machine Control', 'Machine Control'), ('3d Scanner', '3d Scanner')], help_text='Equipment Name', max_length=100)),
                ('date_of_receiving_from_supplier', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(choices=[('Hi Target', 'Hi Targer'), ('TopCon', 'TopCon'), ('Leica', 'Leica'), ('Sokkia', 'Sokkia')], max_length=20)),
                ('owner', models.CharField(choices=[('Company', 'Company'), ('Sub-Contractor', 'Sub-Contractor')], max_length=20)),
                ('base_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('roover_serial', models.CharField(blank=True, help_text='Roover Serial Number', max_length=100, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand')], default='New', max_length=20)),
                ('surveyor_responsible', models.CharField(blank=True, help_text='Name of the surveyor responsible for the equipment', max_length=100, null=True)),
                ('quantity', models.PositiveBigIntegerField(default=1, help_text='Number of Quantity')),
                ('project', models.CharField(blank=True, choices=[('Coastal Road', 'Coastal Road'), ('Sokoto', 'Sokoto')], help_text='Project Name', max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('date_receiving_from_department', models.DateField(blank=True, help_text='Date when the equipment was received from the department', null=True)),
                ('status', models.CharField(blank=True, choices=[('In Store', 'In Store'), ('In Field', 'In Field'), ('With Chief Surveyor', 'With Chief Surveyor'), ('Returning', 'Returning'), ('Delivering', 'Delivering')], default='In Store', help_text='Current status of the equipment', max_length=100, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Delivering', 'Delivering'), ('Cancelled', 'Cancelled')], max_length=10, null=True)),
                ('chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('released', 'Released'), ('returned', 'Returned'), ('status_changed', 'Status Changed')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_equipment_history', to=settings.AUTH_USER_MODEL)),
                ('previous_chief_surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_equipment_history', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.equipmentsinsurvey')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='inventory.equipmentsinsurvey'),
        ),
    ]
