# Generated by Django 5.1.3 on 2025-10-01 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_chainman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='manufacturer_model',
            field=models.CharField(blank=True, help_text='Manufacturer/Model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chainman',
            name='surveyor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='base_serial',
            field=models.CharField(blank=True, help_text='Base Serial Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('New', 'New'), ('Second Hand', 'Second Hand'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='name',
            field=models.CharField(choices=[('GPS Receiver (Base)', 'GPS Receiver (Base)'), ('GPS Receiver (Rover)', 'GPS Receiver (Rover)'), ('Data logger', 'Data logger'), ('External Radio', 'External Radio'), ('Total Station', 'Total Station'), ('Levelling Instrument', 'Levelling Instrument'), ('Eco Sounder', 'Eco Sounder')], help_text='Equipment Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='owner',
            field=models.CharField(choices=[('Hi-Tech', 'Hi-Tech'), ('Sub-Contractor', 'Sub-Contractor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='roover_serial',
            field=models.CharField(blank=True, help_text='Rover Serial Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='supplier',
            field=models.CharField(choices=[('Hi Target V200', 'Hi Target V200'), ('Hi Target', 'Hi Target'), ('Topcon', 'Topcon'), ('Topcon OS-200 Series', 'Topcon OS-200 Series'), ('Topcon OS 103', 'Topcon OS 103'), ('Topcon Hiper VR', 'Topcon Hiper VR'), ('Leica', 'Leica'), ('Leica NA730 plus', 'Leica NA730 plus'), ('Sokkia', 'Sokkia')], max_length=50),
        ),
    ]
