# Generated by Django 5.1.3 on 2024-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(null=True, upload_to='equipment_images/'),
        ),
    ]
