# Generated by Django 5.1.3 on 2025-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipmentsinsurvey_manufacturer_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(choices=[('tracking_rod', 'Tracking Rod'), ('tripod', 'Tripod'), ('external_radio', 'External Radio'), ('car_battery', 'Car battery'), ('base_pole', 'Base pole'), ('tribrach', 'Tribrach'), ('reflector', 'Reflector'), ('levelling_staff', 'Levelling staff'), ('GNSS Battery', 'GNSS Battery'), ('Pole', 'Pole'), ('Mini Prism', 'Mini Prism'), ('Sheet', 'Sheet'), ('Total Station prism', 'Total Station Prism'), ('Radio', 'Radio'), ('gps_extension_bar', 'GPS Extension Bar'), ('bar_port', 'Bar Port'), ('powerbank', 'Powerbank'), ('external_radio_antenna', 'External Radio Antenna'), ('Data Logger', 'Data Logger')], max_length=100),
        ),
    ]
