# Generated by Django 5.1.3 on 2024-11-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('In Field', 'In Field'), ('In Store', 'In Store')], default='In Store', max_length=20),
        ),
    ]
