# Generated by Django 5.1.3 on 2025-10-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_accessory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsinsurvey',
            name='base_serial',
        ),
        migrations.RemoveField(
            model_name='equipmentsinsurvey',
            name='roover_serial',
        ),
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Equipment Serial Number', max_length=100, null=True),
        ),
    ]
