# Generated by Django 5.1.4 on 2025-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='base_serial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number_roover',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
