# Generated by Django 5.1.3 on 2025-10-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_equipmentsinsurvey_base_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsinsurvey',
            name='manufacturer_model',
        ),
    ]
