# Generated by Django 5.1.4 on 2025-02-15 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_equipment_base_serial_equipment_serial_number_roover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentsInSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_receiving_from_supplier', models.DateField()),
                ('supplier', models.CharField(max_length=20)),
                ('base_serial', models.CharField(max_length=100)),
                ('roover_serial', models.CharField(max_length=100)),
                ('data_logger_serial', models.CharField(max_length=100)),
                ('radio_serial', models.CharField(max_length=100)),
                ('surveyor_responsible', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=100)),
                ('date_receiving_from_department', models.DateField()),
                ('chief_surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
