# Generated by Django 5.1.3 on 2025-10-01 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_equipmentsinsurvey_manufacturer_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainman',
            name='surveyor',
        ),
        migrations.AddField(
            model_name='chainman',
            name='date_assigned',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date Assigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chainman',
            name='employee_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Employee ID', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chainman',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active Status'),
        ),
        migrations.AddField(
            model_name='chainman',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='chainman',
            name='name',
            field=models.CharField(help_text='Full Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='serial_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='Equipment Serial Number', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=20, unique=True)),
                ('position', models.CharField(help_text='Job Position', max_length=100)),
                ('department', models.CharField(help_text='Department', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone Number', max_length=15, null=True)),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date Joined')),
                ('is_active', models.BooleanField(default=True, help_text='Active Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chainman',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assigned Personnel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chainmen', to='inventory.personnel'),
        ),
    ]
