# Generated by Django 5.1.4 on 2025-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_equipmentsinsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='status',
            field=models.CharField(choices=[('In Store', 'In Store')], default='In Store', max_length=100),
        ),
    ]
