# Generated by Django 5.1.3 on 2025-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_chainman_surveyor_chainman_date_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='return_comment',
            field=models.TextField(blank=True, help_text='Comment when equipment is returned', null=True),
        ),
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when equipment was returned', null=True),
        ),
    ]
