# Generated by Django 5.1.3 on 2025-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_equipmentsinsurvey_return_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='return_status',
            field=models.CharField(blank=True, choices=[('In Use', 'In Use'), ('Returning', 'Returning'), ('Delivering', 'Delivering'), ('With Chief Surveyor', 'With Chief Surveyor'), ('In Store', 'In Store'), ('Returned', 'Returned')], default='In Store', max_length=20, null=True),
        ),
    ]
