# Generated by Django 5.1.7 on 2025-04-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_equipmentsinsurvey_chief_surveyor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Tripod", "Tripod"),
                            ("Prism", "Prism"),
                            ("Leveling Staff", "Leveling Staff"),
                            ("Tracking Rod", "Tracking Rod"),
                            ("Battery", "Battery"),
                            ("Antenna", "Antenna"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Needs Repair", "Needs Repair"),
                            ("Spoiled", "Spoiled"),
                        ],
                        default="Good",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="inventory.equipment",
                    ),
                ),
            ],
        ),
    ]
