# Generated by Django 5.1.3 on 2025-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_accessory_image_alter_accessory_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('New', 'New'), ('Second Hand', 'Second Hand'), ('Needs Repair', 'Needs Repair'), ('Needs Calibration', 'Needs Calibration')], default='Good', max_length=20),
        ),
    ]
