# Generated by Django 5.1.7 on 2025-04-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_accessory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessories",
                to="inventory.equipmentsinsurvey",
            ),
        ),
    ]
