# Generated by Django 5.1.3 on 2025-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_equipmentsinsurvey_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='condition',
            field=models.CharField(default='Good', help_text='Equipment condition from CSV', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='supplier',
            field=models.CharField(help_text='Manufacturer/Model from CSV', max_length=100),
        ),
    ]
