# Generated by Django 5.1.3 on 2025-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_equipmentsinsurvey_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer from CSV', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(help_text='Accessory name from CSV', max_length=100),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='status',
            field=models.CharField(blank=True, default='Good', help_text='Condition from CSV', max_length=50, null=True),
        ),
    ]
