# Generated by Django 5.1.3 on 2025-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_accessory_manufacturer_alter_accessory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='condition',
            field=models.CharField(blank=True, default='Good', help_text='Physical condition from CSV', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='status',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Bad', 'Bad')], default='Good', max_length=20, null=True),
        ),
    ]
