# Generated by Django 5.1.7 on 2025-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_accessory_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Field", "In Field"),
                    ("Returning", "Returning"),
                    ("In Store", "In Store"),
                ],
                default="In Store",
                max_length=20,
            ),
        ),
    ]
