# Generated by Django 5.1.3 on 2025-10-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_accessory_condition_alter_accessory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Delivering', 'Delivering'), ('Cancelled', 'Cancelled'), ('gap', 'gap')], default='gap', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='project',
            field=models.CharField(blank=True, choices=[('Coastal Road', 'Coastal Road'), ('Sokoto', 'Sokoto'), ('gap', 'gap')], default='gap', help_text='Project Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='return_comment',
            field=models.TextField(blank=True, default='gap', help_text='Comment when equipment is returned', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='surveyor_responsible',
            field=models.CharField(blank=True, default='gap', help_text='Name of the surveyor responsible for the equipment', max_length=100),
        ),
    ]
