# Generated by Django 5.1.7 on 2025-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_equipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentsinsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Store", "In Store"),
                    ("In Field", "In Field"),
                    ("With Chief Surveyor", "With Chief Surveyor"),
                    ("Returning", "Returning"),
                ],
                default="In Store",
                max_length=100,
            ),
        ),
    ]
