# Generated by Django 5.2.4 on 2025-10-12 23:24

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_serial_date_receiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='serial_number',
            field=models.CharField(default=inventory.models.generate_serial_number, help_text='Unique serial number for the accessory', max_length=50, unique=True),
        ),
    ]
