# Generated by Django 5.1.7 on 2025-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_equipmentsinsurvey_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="image",
            field=models.ImageField(null=True, upload_to="accessory_images/"),
        ),
    ]
