# Generated by Django 5.1.7 on 2025-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_accessory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="accessory_images/"
            ),
        ),
    ]
