# Generated by Django 5.2.4 on 2025-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_accessory_assigned_by_accessory_date_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoryhistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Accessory History', 'verbose_name_plural': 'Accessory Histories'},
        ),
        migrations.AlterModelOptions(
            name='equipmenthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Equipment History', 'verbose_name_plural': 'Equipment Histories'},
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='new_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='new_delivery_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='new_equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='new_surveyor_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='previous_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='previous_delivery_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='previous_equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accessoryhistory',
            name='previous_surveyor_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_delivery_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_surveyor_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='previous_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='previous_delivery_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='previous_project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='previous_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='previous_surveyor_responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('released', 'Released to Chief Surveyor'), ('released_to_field', 'Released to Field'), ('returned', 'Returned to Store'), ('status_changed', 'Status Changed'), ('condition_changed', 'Condition Changed'), ('equipment_assigned', 'Assigned to Equipment'), ('equipment_removed', 'Removed from Equipment'), ('image_uploaded', 'Image Uploaded'), ('delivery_cancelled', 'Delivery Cancelled'), ('delivery_received', 'Delivery Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('released', 'Released to Chief Surveyor'), ('released_to_field', 'Released to Field'), ('returned', 'Returned to Store'), ('status_changed', 'Status Changed'), ('condition_changed', 'Condition Changed'), ('surveyor_changed', 'Surveyor Changed'), ('project_changed', 'Project Changed'), ('section_changed', 'Section Changed'), ('delivery_cancelled', 'Delivery Cancelled'), ('delivery_received', 'Delivery Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='previous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
