# Generated by Django 5.1.7 on 2025-04-07 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_accessory_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="date_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                choices=[("In Use", "In Use"), ("Returned", "Returned")],
                default="In Use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="accessory",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returned_accessories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
