# Generated by Django 5.1.7 on 2025-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_accessory_date_returned_accessory_return_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Unique serial number for the accessory",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
