# Generated by Django 5.1.7 on 2025-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_accessory_chief_surveyor_alter_accessory_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="surveyor_responsible",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
