# Generated by Django 5.1.7 on 2025-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_accessory_surveyor_responsible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("In Use", "In Use"),
                    ("Returning", "Returning"),
                    ("Returned", "Returned"),
                ],
                default="In Use",
                max_length=20,
            ),
        ),
    ]
