# Generated by Django 5.1.7 on 2025-04-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_accessoryhistory_equipmenthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In Use", "In Use"),
                    ("Returning", "Returning"),
                    ("In Store", "In Store"),
                    ("Returned", "Returned"),
                ],
                default="In Use",
                max_length=20,
                null=True,
            ),
        ),
    ]
