# Generated by Django 5.1.7 on 2025-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_alter_accessory_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentsinsurvey",
            name="condition",
            field=models.CharField(
                choices=[("Good", "Good"), ("Bad", "Bad")],
                default="Good",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In Use", "In Use"),
                    ("Returning", "Returning"),
                    ("With Chief Surveyor", "With Chief Surveyor"),
                    ("In Store", "In Store"),
                    ("Returned", "Returned"),
                ],
                default="In Use",
                max_length=20,
                null=True,
            ),
        ),
    ]
