# Generated by Django 5.1.7 on 2025-04-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_equipmentsinsurvey_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="surveyor_responsible",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
