# Generated by Django 5.1.7 on 2025-04-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_alter_accessory_surveyor_responsible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Good", "Good"),
                    ("Needs Repair", "Needs Repair"),
                    ("Bad", "Bad"),
                ],
                default="Good",
                max_length=20,
                null=True,
            ),
        ),
    ]
