# Generated by Django 5.1.7 on 2025-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_alter_accessory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
