# Generated by Django 5.1.7 on 2025-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_alter_accessory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In Use", "In Use"),
                    ("Returning", "Returning"),
                    ("With Chief Surveyor", "With Chief Surveyor"),
                    ("In Store", "In Store"),
                    ("Returned", "Returned"),
                ],
                default="Returned",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentsinsurvey",
            name="section",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
