# Generated by Django 5.1.7 on 2025-05-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_alter_accessory_return_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyorengineer",
            name="requested_equipment",
        ),
        migrations.RemoveField(
            model_name="surveyorengineer",
            name="user",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="SurveyorEngineer",
        ),
    ]
