# Generated by Django 5.1.7 on 2025-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_remove_surveyorengineer_requested_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Delivered", "Delivered"),
                    ("Delivering", "Delivering"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipmentsinsurvey",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Delivered", "Delivered"),
                    ("Delivering", "Delivering"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accessory",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In Use", "In Use"),
                    ("Returning", "Returning"),
                    ("Delivering", "Delivering"),
                    ("With Chief Surveyor", "With Chief Surveyor"),
                    ("In Store", "In Store"),
                    ("Returned", "Returned"),
                ],
                default="Returned",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentsinsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Store", "In Store"),
                    ("In Field", "In Field"),
                    ("With Chief Surveyor", "With Chief Surveyor"),
                    ("Returning", "Returning"),
                    ("Delivering", "Delivering"),
                ],
                default="In Store",
                max_length=100,
            ),
        ),
    ]
