# Generated by Django 5.1.7 on 2025-05-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_alter_equipmentsinsurvey_chief_surveyor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentsinsurvey",
            name="project",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
