# Generated by Django 5.1.3 on 2025-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_equipmentsinsurvey_date_of_receiving_from_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(choices=[('tripod', 'Tripod'), ('levelling_staff', 'Levelling Staff'), ('tracking_rod', 'Tracking Rod'), ('reflector', 'Reflector'), ('gps_extension_bar', 'GPS Extension Bar'), ('bar_port', 'Bar Port'), ('powerbank', 'Powerbank'), ('tribach', 'Tribach'), ('external_radio_antenna', 'External Radio Antenna')], max_length=100),
        ),
    ]
