# Generated by Django 5.1.3 on 2025-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_accessory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='name',
            field=models.CharField(help_text='Equipment Name', max_length=100),
        ),
    ]
