# Generated by Django 5.1.3 on 2025-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_equipmentsinsurvey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(choices=[('tripod', 'Tripod'), ('levelling_staff', 'Levelling Staff'), ('Data Logger', 'Data Logger'), ('GNSS Battery', 'GNSS Battery'), ('Pole', 'Pole'), ('Mini Prism', 'Mini Prism'), ('Sheet', 'Sheet'), ('Total Station prism', 'Total Station Prism'), ('Radio', 'Radio'), ('tracking_rod', 'Tracking Rod'), ('reflector', 'Reflector'), ('gps_extension_bar', 'GPS Extension Bar'), ('bar_port', 'Bar Port'), ('powerbank', 'Powerbank'), ('tribach', 'Tribach'), ('external_radio_antenna', 'External Radio Antenna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='base_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='name',
            field=models.CharField(choices=[('GNSS base-roover', 'GNSS base-roover'), ('GNSS rover', 'GNSS rover'), ('GNSS base', 'GNSS base'), ('Total Station', 'Total Station'), ('Level Instruments', 'Level Instrument'), ('Drone', 'Drone'), ('Eco Sounder', 'Eco Sounder'), ('Machine Control', 'Machine Control'), ('3d Scanner', '3d Scanner')], help_text='Equipment Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='supplier',
            field=models.CharField(choices=[('Hi Target', 'Hi Targer'), ('TopCon', 'TopCon'), ('Leica', 'Leica'), ('Sokkia', 'Sokkia')], max_length=20),
        ),
    ]
