# Generated by Django 5.1.3 on 2025-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_accessory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsinsurvey',
            name='owner',
            field=models.CharField(choices=[('Company', 'Company'), ('Sub-Contractor', 'Sub-Contractor')], default='Company', max_length=20),
            preserve_default=False,
        ),
    ]
