# Generated by Django 5.1.3 on 2025-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_equipmentsinsurvey_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='name',
            field=models.CharField(choices=[('GNSS base-roover', 'GNSS base-roover'), ('GNSS roover', 'GNSS roover'), ('GNSS base', 'GNSS base'), ('Total Station', 'Total Station'), ('Level Instruments', 'Level Instrument'), ('Drone', 'Drone'), ('Eco Sounder', 'Eco Sounder'), ('Machine Control', 'Machine Control'), ('3d Scanner', '3d Scanner')], help_text='Equipment Name', max_length=100),
        ),
    ]
