# Generated by Django 5.1.3 on 2025-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_equipmentsinsurvey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='data_logger_serial',
            field=models.CharField(blank=True, help_text='Data Logger Serial Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='date_receiving_from_department',
            field=models.DateField(blank=True, help_text='Date when the equipment was received from the department', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='project',
            field=models.CharField(blank=True, choices=[('Coastal Road', 'Coastal Road'), ('Sokoto', 'Sokoto')], help_text='Project Name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='radio_serial',
            field=models.CharField(blank=True, help_text='Radio Serial Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='roover_serial',
            field=models.CharField(blank=True, help_text='Roover Serial Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='status',
            field=models.CharField(blank=True, choices=[('In Store', 'In Store'), ('In Field', 'In Field'), ('With Chief Surveyor', 'With Chief Surveyor'), ('Returning', 'Returning'), ('Delivering', 'Delivering')], default='In Store', help_text='Current status of the equipment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentsinsurvey',
            name='surveyor_responsible',
            field=models.CharField(blank=True, help_text='Name of the surveyor responsible for the equipment', max_length=100, null=True),
        ),
    ]
