# Generated by Django 5.1.3 on 2025-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_equipmentsinsurvey_data_logger_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number for the accessory', max_length=50, null=True),
        ),
    ]
